name: Run Tests

on: [push, workflow_dispatch]

jobs:
  test:
    # environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      
      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run myp
        run: uv run mypy .

      - name: Run ruff
        run: uvx ruff check .

      - name: Run Tests
        run: uv run pytest --verbose